-- Object     : analytics.page_views
-- Type       : TABLE
-- Class      : CONVERT_WITH_WARNINGS
-- Difficulty : 6/10
-- Rules      : remove_cluster_by, remove_data_retention, number_to_bigint, variant_to_string, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 1
-- SHA-256    : 8fced7b4898d92f8bce3c976a77e1353b55099df4cdc9673f9d2d9c69a0b8cd6
-- Generated  : 2026-03-08T12:18:43.186716
-- ---

CREATE TABLE analytics.page_views (
 event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 event_type STRING NOT NULL,
 event_timestamp TIMESTAMP NOT NULL,
 session_id STRING,
 page_url STRING,
 referrer_url STRING,
 device_type STRING,
 country_code STRING,
 properties STRING
)


USING DELTA;