-- Object     : analytics.funnel_events
-- Type       : TABLE
-- Class      : CONVERT_WITH_WARNINGS
-- Difficulty : 6/10
-- Rules      : remove_data_retention, number_to_bigint, variant_to_string, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 1
-- SHA-256    : b5a2095c2162b86a4ea0d20322a8432c9af5d3f3731ec897d8917e71c0095642
-- Generated  : 2026-03-04T16:31:48.086080
-- ---

CREATE TABLE analytics.funnel_events (
 event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 event_type STRING NOT NULL,
 event_timestamp TIMESTAMP NOT NULL,
 session_id STRING,
 page_url STRING,
 referrer_url STRING,
 device_type STRING,
 country_code STRING,
 properties STRING
)

USING DELTA;