-- Object     : finance.ledger_entries
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_cluster_by, remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : df18cf82a66c97a3b40c8b6bed5311bcf3c39bcf5c4a630b081fdbb6924c0a88
-- Generated  : 2026-03-04T16:31:48.117482
-- ---

CREATE TABLE finance.ledger_entries (
 id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 reference_number STRING NOT NULL,
 amount DECIMAL(14,2) NOT NULL,
 currency_code STRING NOT NULL,
 transaction_date DATE NOT NULL,
 status STRING NOT NULL,
 customer_id BIGINT,
 notes STRING,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP
)


USING DELTA;