-- Object     : finance.payments
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : 8772856b5c0ed8aef4bb29ca27d37fe5dce6503746a2fa229b6614cadde3164b
-- Generated  : 2026-03-08T12:18:43.219707
-- ---

CREATE TABLE finance.payments (
 payment_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 invoice_id BIGINT NOT NULL,
 payment_method STRING NOT NULL,
 amount DECIMAL(14,2) NOT NULL,
 currency_code STRING NOT NULL,
 payment_date DATE NOT NULL,
 status STRING NOT NULL,
 gateway_ref STRING,
 created_at TIMESTAMP NOT NULL
)

USING DELTA;