-- Object     : marketing.email_sends
-- Type       : TABLE
-- Class      : CONVERT_WITH_WARNINGS
-- Difficulty : 6/10
-- Rules      : remove_data_retention, number_to_bigint, variant_to_string, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 1
-- SHA-256    : 0662d1d5b0b65dfdcfd33a9ff4ae217b9d4ede002fba3572dbb8eb8826384a72
-- Generated  : 2026-03-08T12:18:43.237244
-- ---

CREATE TABLE marketing.email_sends (
 event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 event_type STRING NOT NULL,
 event_timestamp TIMESTAMP NOT NULL,
 session_id STRING,
 page_url STRING,
 referrer_url STRING,
 device_type STRING,
 country_code STRING,
 properties STRING
)

USING DELTA;