-- Object     : marketing.conversions
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : d11fa6962a8caf059c396a7ccbdbfad3189b127e8dbd0eaf46fc986b02e74c68
-- Generated  : 2026-03-08T12:18:43.243259
-- ---

CREATE TABLE marketing.conversions (
 conversion_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 campaign_id BIGINT,
 conversion_type STRING NOT NULL,
 revenue DECIMAL(12,2),
 converted_at TIMESTAMP NOT NULL,
 attribution_model STRING
)

USING DELTA;