-- Object     : marketing.attribution_touches
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_cluster_by, remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : f1885bf32f4eeb244e80f65baeb4664fee97eb1a75d02d472b40aebdf0da33c6
-- Generated  : 2026-03-08T12:18:43.246244
-- ---

CREATE TABLE marketing.attribution_touches (
 touch_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 campaign_id BIGINT NOT NULL,
 channel STRING NOT NULL,
 touch_timestamp TIMESTAMP NOT NULL,
 touch_position BIGINT NOT NULL,
 is_converting_touch BOOLEAN NOT NULL,
 credit DECIMAL(5,4)
)


USING DELTA;