-- Object     : marketing.ad_impressions
-- Type       : TABLE
-- Class      : CONVERT_WITH_WARNINGS
-- Difficulty : 6/10
-- Rules      : remove_cluster_by, remove_data_retention, number_to_bigint, variant_to_string, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 1
-- SHA-256    : 85387e968f33635465e5137cc9db9d10cc94bf721ebc79a1f4c5ccff8fe12f17
-- Generated  : 2026-03-08T12:18:43.239247
-- ---

CREATE TABLE marketing.ad_impressions (
 event_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 user_id BIGINT NOT NULL,
 event_type STRING NOT NULL,
 event_timestamp TIMESTAMP NOT NULL,
 session_id STRING,
 page_url STRING,
 referrer_url STRING,
 device_type STRING,
 country_code STRING,
 properties STRING
)


USING DELTA;