-- Object     : marketing.campaigns
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_cluster_by, remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : 8a62afc65fe7d40fad1c14517facbfed990985e3b48a6be8cd3447d7b4379f03
-- Generated  : 2026-03-04T16:31:48.123441
-- ---

CREATE TABLE marketing.campaigns (
 campaign_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 campaign_name STRING NOT NULL,
 channel STRING NOT NULL,
 start_date DATE NOT NULL,
 end_date DATE,
 budget DECIMAL(12,2),
 spend DECIMAL(12,2),
 status STRING NOT NULL,
 created_by STRING,
 created_at TIMESTAMP NOT NULL
)


USING DELTA;