-- Object     : public.products
-- Type       : TABLE
-- Class      : AUTO_CONVERT
-- Difficulty : 4/10
-- Rules      : remove_data_retention, number_to_bigint, number_to_decimal, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 0
-- SHA-256    : 235423b59a39f7df498c1e582776fb67b2d89bef088ca33483702a11501163c4
-- Generated  : 2026-03-08T12:18:43.181183
-- ---

CREATE TABLE public.products (
 product_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 product_name STRING NOT NULL,
 category_id BIGINT NOT NULL,
 sku STRING NOT NULL,
 price DECIMAL(10,2) NOT NULL,
 cost DECIMAL(10,2),
 weight_kg DECIMAL(6,2),
 is_active BOOLEAN NOT NULL,
 created_at TIMESTAMP NOT NULL,
 updated_at TIMESTAMP
)

USING DELTA;