-- Object     : staging.stg_orders_raw
-- Type       : TABLE
-- Class      : CONVERT_WITH_WARNINGS
-- Difficulty : 6/10
-- Rules      : remove_cluster_by, remove_transient, remove_data_retention, number_to_bigint, variant_to_string, timestamp_ntz, varchar_to_string, autoincrement, append_using_delta
-- Warnings   : 1
-- SHA-256    : ce4fc6e67c3042dbad29a410a191d7d13df8fe2f1801bb7389166c806def3c33
-- Generated  : 2026-03-04T16:31:48.093072
-- ---

CREATE TABLE staging.stg_orders_raw (
 row_id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
 raw_payload STRING,
 source_system STRING,
 ingested_at TIMESTAMP NOT NULL,
 file_name STRING,
 batch_id STRING,
 is_processed BOOLEAN NOT NULL
)


USING DELTA;