"""
mock_converter.py — Mock Conversion Engine (implements ConversionEngine)
========================================================================
Reads the mock source catalog and "converts" Redshift SQL to Spark-style SQL
using deterministic rule mappings.

Implements src.interfaces.ConversionEngine so a real LLM-assisted engine
can replace it by changing config.yaml: conversion.engine: "llm".

Run standalone:
    python -m src.mock_converter
"""

import difflib
import hashlib
import json
import re
from datetime import datetime
from pathlib import Path

from src.interfaces import ConversionEngine
from src.config import get_path
from src.logger import get_logger

# ═══════════════════════════════════════════════════════════════════════════════
# Paths
# ═══════════════════════════════════════════════════════════════════════════════

MOCK_DATA_DIR = get_path("mock_data")
ARTIFACTS_DIR = get_path("artifacts")
TRANSPILED_DIR = get_path("transpiled")

# ═══════════════════════════════════════════════════════════════════════════════
# Rewrite rules (Redshift → Databricks/Spark SQL)
# ═══════════════════════════════════════════════════════════════════════════════

REWRITE_RULES = [
    # (label, pattern, replacement, uncertain)
    ("remove_distkey", r"DISTKEY\s*\([^)]*\)", "", False),
    ("remove_sortkey", r"(COMPOUND\s+|INTERLEAVED\s+)?SORTKEY\s*\([^)]*\)", "", False),
    ("remove_diststyle", r"DISTSTYLE\s+(ALL|EVEN|KEY|AUTO)", "", False),
    ("remove_encode", r"ENCODE\s+\w+", "", False),
    ("remove_backup", r"BACKUP\s+(YES|NO)", "", False),
    ("identity_to_generated", r"IDENTITY\s*\((\d+)\s*,\s*(\d+)\)",
     r"GENERATED BY DEFAULT AS IDENTITY (START WITH \1 INCREMENT BY \2)", False),
    ("getdate_to_current_timestamp", r"\bGETDATE\s*\(\)", "CURRENT_TIMESTAMP()", False),
    ("sysdate_to_current_timestamp", r"\bSYSDATE\b", "CURRENT_TIMESTAMP()", False),
    ("nvl_to_coalesce", r"\bNVL\s*\(", "COALESCE(", False),
    ("len_to_length", r"\bLEN\s*\(", "LENGTH(", False),
    ("charindex_to_locate", r"\bCHARINDEX\s*\(", "LOCATE(", False),
    ("varchar_to_string", r"\bVARCHAR\s*\(\d+\)", "STRING", False),
    ("nvarchar_to_string", r"\bNVARCHAR\s*\(\d+\)", "STRING", False),
    ("char_to_string", r"\bCHAR\s*\(\d+\)", "STRING", False),
    ("bpchar_to_string", r"\bBPCHAR\b", "STRING", False),
    ("numeric_to_decimal", r"\bNUMERIC\s*\(", "DECIMAL(", False),
    ("float4_to_float", r"\bFLOAT4\b", "FLOAT", False),
    ("float8_to_double", r"\bFLOAT8\b", "DOUBLE", False),
    ("int2_to_smallint", r"\bINT2\b", "SMALLINT", False),
    ("int4_to_int", r"\bINT4\b", "INT", False),
    ("int8_to_bigint", r"\bINT8\b", "BIGINT", False),
    ("timestamptz_to_timestamp", r"\bTIMESTAMPTZ\b", "TIMESTAMP", False),
    ("random_to_rand", r"\bRANDOM\s*\(\)", "RAND()", False),
    ("strtol_to_conv", r"\bSTRTOL\s*\(", "CONV(", False),
    ("dateadd_rewrite", r"\bDATEADD\s*\(\s*(\w+)\s*,\s*([^,]+)\s*,\s*([^)]+)\)",
     r"DATE_ADD(\3, INTERVAL \2 \1)", False),
    ("date_part_to_extract", r"\bDATE_PART\s*\(\s*'(\w+)'\s*,\s*([^)]+)\)",
     r"EXTRACT(\1 FROM \2)", False),
    ("convert_timezone", r"\bCONVERT_TIMEZONE\s*\(\s*'([^']+)'\s*,\s*'([^']+)'\s*,\s*([^)]+)\)",
     r"FROM_UTC_TIMESTAMP(TO_UTC_TIMESTAMP(\3, '\1'), '\2')", True),
    ("listagg_to_concat_ws",
     r"\bLISTAGG\s*\(([^,]+),\s*'([^']*)'\)\s*WITHIN\s+GROUP\s*\(\s*ORDER\s+BY\s+([^)]+)\)",
     r"CONCAT_WS('\2', COLLECT_LIST(\1))", True),
    ("hashtext_to_hash", r"\bHASHTEXT\s*\(", "HASH(", False),
    ("double_colon_cast", r"(\w+)::(\w+)", r"CAST(\1 AS \2)", False),
]

# Patterns that force MANUAL_REWRITE_REQUIRED
MANUAL_PATTERNS = [
    (r"\bCREATE\s+(OR\s+REPLACE\s+)?PROCEDURE\b", "stored_procedure"),
    (r"\bLANGUAGE\s+plpgsql\b", "plpgsql_function"),
    (r"\bLANGUAGE\s+plpythonu\b", "plpythonu_function"),
    (r"\bCURSOR\b", "cursor_usage"),
    (r"\bRAISE\s+(INFO|WARNING|EXCEPTION)\b", "raise_statement"),
    (r"\bFOR\s+\w+\s+IN\b", "for_loop"),
    (r"\bLOOP\b", "loop_construct"),
    (r"\bIF\s+.*\s+THEN\b", "if_then"),
    (r"\bEXECUTE\s+'", "dynamic_sql"),
    (r"\bCOPY\s+", "copy_command"),
    (r"\bUNLOAD\s*\(", "unload_command"),
    (r"\bCREATE\s+EXTERNAL\s+SCHEMA\b", "external_schema"),
    (r"\bCREATE\s+LIBRARY\b", "create_library"),
]


# ═══════════════════════════════════════════════════════════════════════════════
# Transpiler logic
# ═══════════════════════════════════════════════════════════════════════════════

def _generate_create_ddl(table_info: dict, table_columns: list[dict]) -> str:
    """Build a Redshift-style CREATE TABLE statement from catalog data."""
    schema = table_info["schema"]
    table = table_info["table"]
    diststyle = table_info.get("diststyle", "AUTO")

    lines = [f'CREATE TABLE {schema}.{table} (']
    col_lines = []
    for col in table_columns:
        nullable = "" if col.get("nullable") == "YES" else " NOT NULL"
        enc = f" ENCODE {col.get('encoding', 'raw').upper()}" if col.get("encoding") else ""
        col_lines.append(f'    {col["column"]} {col["data_type"]}{nullable}{enc}')
    lines.append(",\n".join(col_lines))
    lines.append(f") DISTSTYLE {diststyle};")
    return "\n".join(lines)


def transpile_sql(source_sql: str, object_name: str = "") -> dict:
    """
    Apply rewrite rules to a single SQL string.

    Returns dict with: transpiled_sql, classification, difficulty, applied_rules,
    warnings, manual_flags, diff.
    """
    result_sql = source_sql
    applied_rules = []
    warnings = []
    manual_flags = []

    # Check for manual-rewrite patterns first
    for pattern, flag_name in MANUAL_PATTERNS:
        if re.search(pattern, source_sql, re.IGNORECASE):
            manual_flags.append(flag_name)

    # Apply rewrite rules
    for label, pattern, replacement, uncertain in REWRITE_RULES:
        new_sql = re.sub(pattern, replacement, result_sql, flags=re.IGNORECASE)
        if new_sql != result_sql:
            applied_rules.append(label)
            if uncertain:
                warnings.append(f"Rule '{label}' may need manual review")
            result_sql = new_sql

    # Clean up double whitespace from removals
    result_sql = re.sub(r'\n\s*\n\s*\n', '\n\n', result_sql)
    result_sql = re.sub(r'  +', ' ', result_sql)
    result_sql = result_sql.strip()

    # Classification
    if manual_flags:
        classification = "MANUAL_REWRITE_REQUIRED"
    elif warnings:
        classification = "CONVERT_WITH_WARNINGS"
    else:
        classification = "AUTO_CONVERT"

    # Difficulty score (1-10)
    difficulty = 1
    difficulty += min(len(applied_rules), 3)
    difficulty += len(warnings) * 2
    if manual_flags:
        difficulty = max(difficulty, 8)
        difficulty += min(len(manual_flags) - 1, 2)
    join_count = len(re.findall(r'\bJOIN\b', source_sql, re.IGNORECASE))
    difficulty += min(join_count, 2)
    if re.search(r'\bOVER\s*\(', source_sql, re.IGNORECASE):
        difficulty += 1
    if len(source_sql) > 2000:
        difficulty += 1
    difficulty = min(difficulty, 10)

    # Unified diff
    diff = "\n".join(difflib.unified_diff(
        source_sql.splitlines(),
        result_sql.splitlines(),
        fromfile=f"source/{object_name}",
        tofile=f"databricks/{object_name}",
        lineterm="",
    ))

    sha = hashlib.sha256(source_sql.encode()).hexdigest()

    return {
        "object_name": object_name,
        "classification": classification,
        "difficulty": difficulty,
        "applied_rules": applied_rules,
        "warnings": warnings,
        "manual_flags": manual_flags,
        "source_sql": source_sql,
        "transpiled_sql": result_sql,
        "diff": diff,
        "sha256": sha,
    }


# ═══════════════════════════════════════════════════════════════════════════════
# Adapter class (implements ConversionEngine)
# ═══════════════════════════════════════════════════════════════════════════════

class MockConversionEngine(ConversionEngine):
    """Mock implementation using deterministic regex-based rewrite rules."""

    def __init__(self):
        self.log = get_logger("mock_converter", "mock_converter.log")

    def transpile(self, source_sql: str, object_name: str = "") -> dict:
        return transpile_sql(source_sql, object_name)

    def run_full_conversion(self, catalog: dict) -> dict:
        self.log.step("conversion", "started")
        TRANSPILED_DIR.mkdir(parents=True, exist_ok=True)

        report_entries = []
        flagged_manual = []
        total_warnings = 0

        # Transpile table DDL
        tables_by_key = {}
        for t in catalog["tables"]:
            tables_by_key[(t["schema"], t["table"])] = t

        cols_by_table = {}
        for c in catalog["columns"]:
            key = (c["schema"], c["table"])
            cols_by_table.setdefault(key, []).append(c)

        for key, table_info in tables_by_key.items():
            schema, table = key
            table_cols = sorted(cols_by_table.get(key, []), key=lambda c: c["ordinal_position"])
            source_ddl = _generate_create_ddl(table_info, table_cols)

            result = self.transpile(source_ddl, f"{schema}.{table}")
            if "USING DELTA" not in result["transpiled_sql"]:
                result["transpiled_sql"] = result["transpiled_sql"].rstrip().rstrip(";")
                result["transpiled_sql"] += "\nUSING DELTA;"
                if "append_using_delta" not in result["applied_rules"]:
                    result["applied_rules"].append("append_using_delta")
            result["object_type"] = "TABLE"

            out_path = TRANSPILED_DIR / f"{schema}_{table}.sql"
            header = (
                f"-- Object     : {schema}.{table}\n"
                f"-- Type       : TABLE\n"
                f"-- Class      : {result['classification']}\n"
                f"-- Difficulty : {result['difficulty']}/10\n"
                f"-- Rules      : {', '.join(result['applied_rules'])}\n"
                f"-- Warnings   : {len(result['warnings'])}\n"
                f"-- SHA-256    : {result['sha256']}\n"
                f"-- Generated  : {datetime.now().isoformat()}\n"
                f"-- ---\n\n"
            )
            out_path.write_text(header + result["transpiled_sql"], encoding="utf-8")
            report_entries.append(result)
            total_warnings += len(result["warnings"])

        # Transpile views
        for v in catalog.get("views", []):
            name = f"{v['schema']}.{v['view_name']}"
            result = self.transpile(v["definition"], name)
            result["object_type"] = "VIEW"
            out_path = TRANSPILED_DIR / f"{v['schema']}_{v['view_name']}.sql"
            header = (
                f"-- Object     : {name}\n"
                f"-- Type       : VIEW\n"
                f"-- Class      : {result['classification']}\n"
                f"-- Difficulty : {result['difficulty']}/10\n"
                f"-- Generated  : {datetime.now().isoformat()}\n"
                f"-- ---\n\n"
            )
            out_path.write_text(header + result["transpiled_sql"], encoding="utf-8")
            report_entries.append(result)
            total_warnings += len(result["warnings"])

        # Transpile procs
        for p in catalog.get("procs", []):
            name = f"{p['schema']}.{p['name']}"
            result = self.transpile(p["source"], name)
            result["object_type"] = "PROCEDURE"
            report_entries.append(result)
            if result["classification"] == "MANUAL_REWRITE_REQUIRED":
                flagged_manual.append({
                    "object": name, "type": "PROCEDURE",
                    "flags": result["manual_flags"],
                    "guidance": "Rewrite as Databricks notebook or workflow. "
                                "PL/pgSQL control flow has no Spark SQL equivalent.",
                })
            total_warnings += len(result["warnings"])

        # Transpile UDFs
        for u in catalog.get("udfs", []):
            name = f"{u['schema']}.{u['name']}"
            result = self.transpile(u["source"], name)
            result["object_type"] = "UDF"
            report_entries.append(result)
            total_warnings += len(result["warnings"])

        # Build report
        class_counts = {}
        for r in report_entries:
            c = r["classification"]
            class_counts[c] = class_counts.get(c, 0) + 1

        report = {
            "generated_at": datetime.now().isoformat(),
            "summary": {
                "total_objects": len(report_entries),
                "classifications": class_counts,
                "total_warnings": total_warnings,
                "manual_rewrite_count": class_counts.get("MANUAL_REWRITE_REQUIRED", 0),
            },
            "objects": [
                {
                    "object_name": r["object_name"],
                    "object_type": r["object_type"],
                    "classification": r["classification"],
                    "difficulty": r["difficulty"],
                    "applied_rules": r["applied_rules"],
                    "warnings": r["warnings"],
                    "manual_flags": r.get("manual_flags", []),
                    "diff": r["diff"],
                    "sha256": r["sha256"],
                }
                for r in report_entries
            ],
            "flagged_manual_items": flagged_manual,
        }

        self.log.step("conversion", "completed",
                      total_objects=len(report_entries),
                      classifications=class_counts,
                      total_warnings=total_warnings)
        return report

    def save(self, report: dict) -> dict:
        self.log.step("save", "started")
        report_path = ARTIFACTS_DIR / "conversion_report.json"
        report_path.write_text(json.dumps(report, indent=2, default=str), encoding="utf-8")
        self.log.step("save", "completed", report_path=str(report_path))
        return {"conversion_report": str(report_path), "transpiled_dir": str(TRANSPILED_DIR)}


# ═══════════════════════════════════════════════════════════════════════════════
# Standalone entrypoint
# ═══════════════════════════════════════════════════════════════════════════════

def run():
    """Read mock catalog, transpile everything, write outputs."""
    catalog_path = MOCK_DATA_DIR / "source_catalog.json"
    if not catalog_path.exists():
        print("ERROR: mock_data/source_catalog.json not found. Run mock_redshift.py first.")
        return

    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))

    engine = MockConversionEngine()
    report = engine.run_full_conversion(catalog)
    paths = engine.save(report)

    s = report["summary"]
    cc = s["classifications"]
    print(f"Transpiled SQL       : {paths['transpiled_dir']}")
    print(f"  Tables             : {sum(1 for o in report['objects'] if o['object_type'] == 'TABLE')}")
    print(f"  Views              : {sum(1 for o in report['objects'] if o['object_type'] == 'VIEW')}")
    print(f"  Procedures         : {sum(1 for o in report['objects'] if o['object_type'] == 'PROCEDURE')}")
    print(f"  UDFs               : {sum(1 for o in report['objects'] if o['object_type'] == 'UDF')}")
    print(f"Conversion report    : {paths['conversion_report']}")
    print(f"  AUTO_CONVERT       : {cc.get('AUTO_CONVERT', 0)}")
    print(f"  CONVERT_WITH_WARNINGS : {cc.get('CONVERT_WITH_WARNINGS', 0)}")
    print(f"  MANUAL_REWRITE     : {cc.get('MANUAL_REWRITE_REQUIRED', 0)}")
    print(f"  Total warnings     : {s['total_warnings']}")
    print(f"  Manual items       : {len(report.get('flagged_manual_items', []))}")


if __name__ == "__main__":
    run()
