"""
catalog.py — Source catalog data endpoints
"""

import json
from typing import Optional

from fastapi import APIRouter, Query

from api.dependencies import MOCK_DATA_DIR, ARTIFACTS_DIR, PROJECT_DIR, CurrentUser

router = APIRouter(prefix="/api/catalog", tags=["catalog"])


def _get_config() -> dict:
    """Load current configuration"""
    config_file = PROJECT_DIR / "config.yaml"
    if config_file.exists():
        import yaml
        with open(config_file, 'r', encoding='utf-8') as f:
            return yaml.safe_load(f) or {}
    return {}


def _load_catalog() -> dict:
    """Load catalog from appropriate source based on config"""
    config = _get_config()
    # Config structure is: source.adapter (not source_adapter at root)
    source_config = config.get('source', {})
    source_adapter = source_config.get('adapter', 'mock_snowflake')

    print(f"[DEBUG _load_catalog] source_adapter: {source_adapter}")

    # Determine which catalog to load
    if source_adapter.startswith('mock_'):
        # Use mock data
        path = MOCK_DATA_DIR / "source_catalog.json"
        print(f"[DEBUG _load_catalog] Using MOCK path: {path}")
    else:
        # Use real data from artifacts (generated by pipeline)
        path = ARTIFACTS_DIR / "source_catalog.json"
        print(f"[DEBUG _load_catalog] Using REAL path: {path}")

    print(f"[DEBUG _load_catalog] Path exists: {path.exists()}")

    if path.exists():
        catalog = json.loads(path.read_text(encoding="utf-8"))
        schemas_in_catalog = sorted(set(t['schema'] for t in catalog.get('tables', [])))
        print(f"[DEBUG _load_catalog] Schemas in catalog: {schemas_in_catalog}")
        return catalog

    # Return empty catalog with helpful message
    print(f"[DEBUG _load_catalog] No catalog file found")
    return {
        "tables": [],
        "columns": [],
        "constraints": [],
        "message": "No catalog data available. Run the pipeline to generate catalog."
    }


@router.get("")
def get_catalog(
    _user: CurrentUser,
    schemas: Optional[str] = Query(None, description="Comma-separated schema names"),
):
    catalog = _load_catalog()
    # Only filter if schemas is provided and not empty
    if schemas and schemas.strip():
        schema_set = set(s.strip() for s in schemas.split(",") if s.strip())
        if schema_set:  # Only filter if we have valid schemas
            catalog["tables"] = [
                t for t in catalog.get("tables", []) if t.get("schema") in schema_set
            ]
            catalog["columns"] = [
                c for c in catalog.get("columns", []) if c.get("schema") in schema_set
            ]
            catalog["constraints"] = [
                c for c in catalog.get("constraints", []) if c.get("schema") in schema_set
            ]
    return catalog


@router.get("/schemas")
def get_schemas(_user: CurrentUser):
    """Get available schemas - first check cache from connection test, then check catalog"""
    import json

    # First, check if we have cached schemas from connection test
    cache_file = ARTIFACTS_DIR / "available_schemas.json"
    print(f"[DEBUG] Checking cache file: {cache_file}")
    print(f"[DEBUG] File exists: {cache_file.exists()}")

    if cache_file.exists():
        try:
            with open(cache_file, 'r', encoding='utf-8') as f:
                data = json.load(f)
                schemas = data.get("schemas", [])
                print(f"[DEBUG] Schemas from cache: {schemas}")
                if schemas:
                    print(f"[DEBUG] Returning cached schemas")
                    return {"schemas": sorted(schemas)}
        except Exception as e:
            print(f"[DEBUG] Error reading cache: {e}")
            pass

    # Fall back to catalog (after pipeline has run)
    print(f"[DEBUG] Falling back to catalog")
    catalog = _load_catalog()
    schemas = sorted({t["schema"] for t in catalog.get("tables", [])})
    print(f"[DEBUG] Schemas from catalog: {schemas}")
    return {"schemas": schemas}


@router.get("/relationships")
def get_relationships(
    _user: CurrentUser,
    schemas: Optional[str] = Query(None, description="Comma-separated schema names"),
):
    """Get foreign key relationships from catalog"""
    catalog = _load_catalog()
    constraints = catalog.get("constraints", [])

    # Filter for foreign keys
    fk_constraints = [
        c for c in constraints
        if c.get("constraint_type") == "FOREIGN KEY"
    ]

    # Apply schema filter if provided and not empty
    if schemas and schemas.strip():
        schema_set = set(s.strip() for s in schemas.split(",") if s.strip())
        if schema_set:  # Only filter if we have valid schemas
            fk_constraints = [
                c for c in fk_constraints
                if c.get("schema") in schema_set
            ]

    # Format relationships for frontend
    relationships = []
    for fk in fk_constraints:
        relationships.append({
            "from_schema": fk.get("schema", ""),
            "from_table": fk.get("table", ""),
            "from_column": fk.get("column", ""),
            "to_schema": fk.get("ref_schema", ""),
            "to_table": fk.get("ref_table", ""),
            "to_column": fk.get("ref_column", ""),
            "constraint_name": fk.get("constraint_name", ""),
        })

    return {
        "relationships": relationships,
        "total_count": len(relationships)
    }


@router.get("/lineage")
def get_lineage(
    _user: CurrentUser,
    schemas: Optional[str] = Query(None, description="Comma-separated schema names"),
):
    """Get table lineage based on foreign key relationships"""
    catalog = _load_catalog()
    constraints = catalog.get("constraints", [])
    tables = catalog.get("tables", [])

    # Separate PK and FK constraints
    pk_constraints = [
        c for c in constraints
        if c.get("constraint_type") == "PRIMARY KEY"
    ]
    fk_constraints = [
        c for c in constraints
        if c.get("constraint_type") == "FOREIGN KEY"
    ]

    # Apply schema filter if provided and not empty
    if schemas and schemas.strip():
        schema_set = set(s.strip() for s in schemas.split(",") if s.strip())
        if schema_set:  # Only filter if we have valid schemas
            pk_constraints = [
                c for c in pk_constraints
                if c.get("schema") in schema_set
            ]
            fk_constraints = [
                c for c in fk_constraints
                if c.get("schema") in schema_set
            ]
            tables = [t for t in tables if t.get("schema") in schema_set]

    # Build PK map: table_id -> [pk_columns]
    pk_map = {}
    for pk in pk_constraints:
        table_id = f"{pk.get('schema', '')}.{pk.get('table', '')}"
        if table_id not in pk_map:
            pk_map[table_id] = []
        pk_map[table_id].append(pk.get("column", ""))

    # Build FK map: table_id -> [fk_columns]
    fk_map = {}
    for fk in fk_constraints:
        table_id = f"{fk.get('schema', '')}.{fk.get('table', '')}"
        if table_id not in fk_map:
            fk_map[table_id] = []
        fk_map[table_id].append({
            "column": fk.get("column", ""),
            "references": f"{fk.get('ref_schema', '')}.{fk.get('ref_table', '')}.{fk.get('ref_column', '')}",
            "ref_table": f"{fk.get('ref_schema', '')}.{fk.get('ref_table', '')}",
            "ref_column": fk.get('ref_column', ''),
        })

    # Build nodes (tables) with PK and FK information
    nodes = []
    table_set = set()
    for table in tables:
        # Use 'table' field (not 'name') - catalog structure has 'table' key
        table_name = table.get('table') or table.get('name', '')
        table_id = f"{table.get('schema', '')}.{table_name}"
        table_set.add(table_id)
        nodes.append({
            "id": table_id,
            "schema": table.get("schema", ""),
            "table": table_name,
            "type": table.get("type", "TABLE"),
            "row_count": table.get("row_count", 0),
            "primary_keys": pk_map.get(table_id, []),
            "foreign_keys": fk_map.get(table_id, []),
        })

    # Build edges (relationships)
    edges = []
    for fk in fk_constraints:
        from_table = f"{fk.get('schema', '')}.{fk.get('table', '')}"
        to_table = f"{fk.get('ref_schema', '')}.{fk.get('ref_table', '')}"

        # Only include edges where both tables exist
        if from_table in table_set and to_table and to_table != ".":
            edges.append({
                "from": from_table,
                "to": to_table,
                "type": "foreign_key",
                "from_column": fk.get("column", ""),
                "to_column": fk.get("ref_column", ""),
                "label": f"{fk.get('column', '')} → {fk.get('ref_column', '')}",
            })

    return {
        "nodes": nodes,
        "edges": edges,
        "stats": {
            "total_tables": len(nodes),
            "total_relationships": len(edges),
        }
    }
